### ISSUE TITLE
JsConnectController renames existing users

### ISSUE THREAD

**Issue by JanLenoch** [petrsvihlik/jsConnectAspNetCoreMvc#4]
When getting a user object from the VanillaApiClient, the JsConnectController might get null (instead of a user, see https://github.com/petrsvihlik/jsConnectAspNetCoreMvc/blob/master/src/jsConnectAspNetCoreMvc/Controllers/JsConnectController.cs#L129) just because of an arbitrary error HTTP response. Then, the controller acts like the user does not exist, and, when it finds it exists in the subsequent request, it adds the numeric suffix to it.

The fix would be to distinguish the error codes in the VanillaApiClient, returning more detailed info to the controller and making it more resilient.

**Comment by petrsvihlik** [comment]
stale -> closing
